apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: default
      containers:
        - name: backend-api
          image: gcr.io/summariser-prototype/backend-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:file:/data/h2db/summarizer"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.h2.Driver"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
            - name: HUGGINGFACE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HUGGINGFACE_API_TOKEN
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ANTHROPIC_API_KEY
            - name: MISTRAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MISTRAL_API_KEY
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/secrets/service-account-key.json
            - name: PYTHON_PATH
              value: "/usr/bin/python3"
            - name: METRICS_SCRIPT_PATH
              value: "/app/scripts/metrics_calculator.py"
          resources:
            requests:
              memory: "768Mi"
              cpu: "750m"
            limits:
              memory: "1.5Gi"
              cpu: "1.5"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          volumeMounts:
            - name: h2-storage
              mountPath: /data/h2db
            - name: gcp-credentials
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: h2-storage
          emptyDir: {}
        - name: gcp-credentials
          secret:
            secretName: gcp-service-account
