package com.local.SummarizerOrchestrator.dtos;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class SummarizationResponseDTO {
    private String providerName; // Name of the provider (e.g., "Hugging Face", "Vertex AI")
    private String summary; // The summary generated by the provider
}
